driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6.7
- name: centos-7.2
- name: fedora-22
- name: fedora-23

suites:
- name: default
  run_list:
    - recipe[selinux_module_test::create]
    - recipe[selinux_module_test::remove]
    - recipe[selinux_state_test]
  attributes: {}
