Lint/AssignmentInCondition:
  Exclude:
    - 'libraries/selinux_file_helper.rb'
    - 'libraries/selinux_module_helper.rb'

Lint/UselessAssignment:
  Exclude:
    - 'providers/module.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'libraries/selinux_module_helper.rb'

Style/RegexpLiteral:
  Exclude:
    - 'providers/module.rb'
